### ISSUE TITLE
Cannot load such file -- posix/spawn

### ISSUE THREAD

**Issue by tf** [thoughtbot/cocaine#82]
Since `0.5.6` I get "cannot load such file -- posix/spawn" when using the gem with paperclip. 

This [change](https://github.com/thoughtbot/cocaine/commit/80b0b8f75fe45b9491b8ab4287d915fe251d900d#diff-396fec55022bdf1e3163824f691e9e4bR47) changed `rescue LoadError` to simply `rescue`. But `LoadError` is not a `StandardError`. Hence the detection is broken.

**Comment by jyurek** [comment]
Thanks for reporting this. I'm fixing it now and will push 0.5.7 ASAP!

**Comment by tf** [comment]
Already pushed a PR for your review.

**Comment by jyurek** [comment]
Thank you. Again, i really appreciate it, though I'd already gotten halfway through it when you reported.
