### ISSUE TITLE
How to deal with paths containing special characters?

### ISSUE THREAD

**Issue by paulmenzel** [thoughtbot/cocaine#92]
Do path names to be manually quoted, or will Cocaine take care of that? Currently passing `#{my_filename}` where `my_filename = "test(c).c"` then it won’t be found on the command line.

Do I need to manually do `'#{my_filename}'`?

**Comment by paulmenzel** [comment]
It solved itself, using interpolated arguments. Sorry for the noise.

**Comment by jyurek** [comment]
Yup, the interpolated arguments are exactly what this is for! Glad it worked out for you!
