### ISSUE TITLE
Deadlock when spawned process writes to stderr

### ISSUE THREAD

**Issue by kilink** [thoughtbot/cocaine#96]
When a process spawned by Cocaine writes sufficient data to stderr, both the processes will hang indefinitely. This is because Cocaine is blocked reading from stdin, while the process eventually blocks writing to stderr when the internal buffer for the pipe becomes full.

The issue can be reproduced with the following trivial script:
```ruby
#!/usr/bin/env ruby

1000.times do
  STDERR.puts "*" * 1000
end
```

Called via Cocaine, it blocks:
```ruby
Cocaine::CommandLine.new("./hang.rb").run # hangs forever
```

Using strace, you'll be able to see that the invoked process is blocked in a write syscall on the STDERR file descriptor. The other giveaway is that this does not block:

```ruby
Cocaine::CommandLine.new("./hang.rb", "", swallow_stderr: true).run
```

Obviously that's not ideal, since we may want to capture both stdout and stderr.

This [Zendesk blog post](https://medium.com/zendesk-engineering/running-a-child-process-in-ruby-properly-febd0a2b6ec8) touches on the issue briefly in the section entitled "Bonus round: avoiding deadlocks." The solution is to avoid making blocking calls like read, and using IO::select in a loop to figure out which file descriptors are ready to be read from. [Here is how it is implemented in the subprocess gem](https://github.com/stripe/subprocess/blob/master/lib/subprocess.rb#L361).

I see potentially fixing this in [Multipipe#read](https://github.com/thoughtbot/cocaine/blob/master/lib/cocaine/command_line/multi_pipe.rb#L31), or by adding a new runner that uses the subprocess gem. Thoughts?

**Comment by mmangino** [comment]
Did you ever create this runner? If not, I'm going to give it a shot. We're having the same issue.

**Comment by joshuapinter** [comment]
Did this ever get fixed? Running into the same problem transcoding medium sized files (26mbs+).

Thanks!

**Comment by joshuapinter** [comment]
FYI, we tried @mmangino's branch and it works great in production for larger files. No more deadlocks. You can see more of it here: https://github.com/thoughtbot/cocaine/pull/97

**Comment by jyurek** [comment]
The PR that fixes this has been moved to https://github.com/thoughtbot/terrapin/pull/5. I'll close this and any necessary discussion on this point can be found there. Thanks!
