### ISSUE TITLE
Name Change?

### ISSUE THREAD

**Issue by ThoughtbotThom** [thoughtbot/cocaine#99]
Every so often I see dubious feedback on this library's name:
https://twitter.com/tcollen/status/689167094424801280
https://twitter.com/6171742/status/917891501170089986

It's kind of cringe and sophomoric; thoughts on changing it?

**Comment by jyurek** [comment]
OK I'm open to changing the name. What's a good name to change to?

`shell run`
`tortoise`
`run_like_shell`

**Comment by graywolf** [comment]
But the name is funny...

**Comment by doyle** [comment]
I'm in favor of renaming this gem as well. I work for a healthcare company and worry what would happen should someone audit our code base and find that it includes _cocaine_ 😟 . FWIW I think `tortoise` is a great name.

**Comment by arbonap** [comment]
`tortoise` is an excellent choice IMO 🐢

**Comment by jdax** [comment]
I am in favor of a name change, and the emoji possibilities are quite awesome for `tortoise`

**Comment by croaky** [comment]
Maybe @david would be willing to part with the `runner` gem? Is that an active project? https://rubygems.org/gems/runner points to a 404 at https://github.com/david/runner

**Comment by jyurek** [comment]
Sadly, tortoise is taken and looks active. I'll see about messaging @david to see if he'll part with `runner`

**Comment by doyle** [comment]
`run_like_shell` isn't taken, also `conch` looks inactive if you want to stick with the shell theme.

**Comment by david** [comment]
I'm fine with passing `runner` over to you if you decide you'd like to use it.

**Comment by jyurek** [comment]
Oh! Thank you very much. I'll be in touch if that's what I decide on.

**Comment by johnnyshields** [comment]
How about `cocaine_bot`?

**Comment by michalg-** [comment]
`cocaine_girl`, no?

**Comment by panSarin** [comment]
Current name is fine, and many ppl already know that name so changing it can be confusing. Let's don't go crazy about whole political correctness thing.

**Comment by johnnyshields** [comment]
How about `heroin_heroine`?

**Comment by alosada** [comment]
I'd how change it to `meth`  or other snorted drug, jsut to be a smarthash

**Comment by jyurek** [comment]
So, `tortoise` being taken, I think the name I'm going to use is Terrapin, which is another name for turtles. Specifically ones that live in fresh or brackish water. :turtle:

Re: Political correctness. It's not about that. I'm simply tired of the name, and I find myself agreeing with the people who call it a simply bad name.

**Comment by jyurek** [comment]
https://github.com/thoughtbot/cocaine/pull/103
